# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    # 手動で意味のある順でソートしたいので無効化
    sort_pub_dependencies: false

analyzer:
  plugins:
    - custom_lint
  exclude:
    # freezedの自動生成ファイルを除外する
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"
  errors:
    # freezedのJsonKeyのエラーを無視する
    # ref: https://github.com/rrousselGit/freezed/issues/488
    invalid_annotation_target: ignore
