name: Flutter Build

on:
  push:
    tags:
      - v*

jobs:
  flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.9"
          channel: "stable"
          cache: true
      - name: Create dot env file
        shell: bash
        run: |
          touch .env
          echo "GITHUB_TOKEN=hogehoge" >> .env
      - name: Read tag version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          BUILD_NAME=$(echo $TAG | sed -E 's/v([0-9]+\.[0-9]+\.[0-9]+)\+.*/\1/')
          BUILD_NUMBER=$(echo $TAG | sed -E 's/v[0-9]+\.[0-9]+\.[0-9]+\+([0-9]+)/\1/')

          echo "BUILD_NAME=$BUILD_NAME" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

      - run: flutter build apk --dart-define-from-file=dart_defines/prod.json --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
